export const matchData = [
    // Friday, October 25, 2024
    {
        id: "1",
        date: "Oct 25",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 3,
        awayTeam: "Kurtis",
        awayColor: "black",
        awayScore: 3,
    },
    {
        id: "2",
        date: "Oct 25",
        homeTeam: "Nick",
        homeColor: "green",
        homeScore: 5,
        awayTeam: "Ted",
        awayColor: "red",
        awayScore: 2,
    },
    {
        id: "3",
        date: "Oct 25",
        homeTeam: "Josh",
        homeColor: "blue",
        homeScore: 7,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 3,
    },
    // Friday, November 01, 2024
    {
        id: "4",
        date: "Nov 01",
        homeTeam: "Ted",
        homeColor: "red",
        homeScore: 1,
        awayTeam: "Josh",
        awayColor: "blue",
        awayScore: 10,
    },
    {
        id: "5",
        date: "Nov 01",
        homeTeam: "Kurtis",
        homeColor: "black",
        homeScore: 3,
        awayTeam: "Nick",
        awayColor: "green",
        awayScore: 6,
    },
    {
        id: "6",
        date: "Nov 01",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 2,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 7,
    },
    // Friday, November 08, 2024
    {
        id: "7",
        date: "Nov 08",
        homeTeam: "Nick",
        homeColor: "green",
        homeScore: 4,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 5,
    },
    {
        id: "8",
        date: "Nov 08",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 4,
        awayTeam: "Josh",
        awayColor: "blue",
        awayScore: 8,
    },
    {
        id: "9",
        date: "Nov 08",
        homeTeam: "Kurtis",
        homeColor: "black",
        homeScore: 11,
        awayTeam: "Ted",
        awayColor: "red",
        awayScore: 1,
    },
    // Friday, November 15, 2024
    {
        id: "10",
        date: "Nov 15",
        homeTeam: "Kurtis",
        homeColor: "black",
        homeScore: 1,
        awayTeam: "Josh",
        awayColor: "blue",
        awayScore: 6,
    },
    {
        id: "11",
        date: "Nov 15",
        homeTeam: "Ted",
        homeColor: "red",
        homeScore: 0,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 12,
    },
    {
        id: "12",
        date: "Nov 15",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 3,
        awayTeam: "Nick",
        awayColor: "green",
        awayScore: 11,
    },
    // Friday, November 22, 2024
    {
        id: "13",
        date: "Nov 22",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 3,
        awayTeam: "Ted",
        awayColor: "red",
        awayScore: 3,
    },
    {
        id: "14",
        date: "Nov 22",
        homeTeam: "Kurtis",
        homeColor: "black",
        homeScore: 2,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 5,
    },
    {
        id: "15",
        date: "Nov 22",
        homeTeam: "Nick",
        homeColor: "green",
        homeScore: 6,
        awayTeam: "Josh",
        awayColor: "blue",
        awayScore: 5,
    },
    // Friday, November 29, 2024
    {
        id: "16",
        date: "Nov 29",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 3,
        awayTeam: "Kurtis",
        awayColor: "black",
        awayScore: 4,
    },
    {
        id: "17",
        date: "Nov 29",
        homeTeam: "Nick",
        homeColor: "green",
        homeScore: 11,
        awayTeam: "Ted",
        awayColor: "red",
        awayScore: 0,
    },
    {
        id: "18",
        date: "Nov 29",
        homeTeam: "Josh",
        homeColor: "blue",
        homeScore: 2,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 1,
    },
    // Friday, December 06, 2024
    {
        id: "19",
        date: "Dec 06",
        homeTeam: "Ted",
        homeColor: "red",
        homeScore: 2,
        awayTeam: "Josh",
        awayColor: "blue",
        awayScore: 10,
    },
    {
        id: "20",
        date: "Dec 06",
        homeTeam: "Kurtis",
        homeColor: "black",
        homeScore: 3,
        awayTeam: "Nick",
        awayColor: "green",
        awayScore: 5,
    },
    {
        id: "21",
        date: "Dec 06",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 3,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 4,
    },
    // Friday, December 13, 2024
    {
        id: "22",
        date: "Dec 13",
        homeTeam: "Nick",
        homeColor: "green",
        homeScore: 4,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 8,
    },
    {
        id: "23",
        date: "Dec 13",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 3,
        awayTeam: "Josh",
        awayColor: "blue",
        awayScore: 6,
    },
    {
        id: "24",
        date: "Dec 13",
        homeTeam: "Kurtis",
        homeColor: "black",
        homeScore: 4,
        awayTeam: "Ted",
        awayColor: "red",
        awayScore: 4,
    },
    // Friday, December 20, 2024
    {
        id: "25",
        date: "Dec 20",
        homeTeam: "Kurtis",
        homeColor: "black",
        homeScore: 4,
        awayTeam: "Josh",
        awayColor: "blue",
        awayScore: 12,
    },
    {
        id: "26",
        date: "Dec 20",
        homeTeam: "Ted",
        homeColor: "red",
        homeScore: 1,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 7,
    },
    {
        id: "27",
        date: "Dec 20",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 4,
        awayTeam: "Nick",
        awayColor: "green",
        awayScore: 14,
    },
    // Friday, January 03, 2025
    {
        id: "28",
        date: "Jan 03",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 2,
        awayTeam: "Ted",
        awayColor: "red",
        awayScore: 4,
    },
    {
        id: "29",
        date: "Jan 03",
        homeTeam: "Kurtis",
        homeColor: "black",
        homeScore: 7,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 3,
    },
    {
        id: "30",
        date: "Jan 03",
        homeTeam: "Nick",
        homeColor: "green",
        homeScore: 2,
        awayTeam: "Josh",
        awayColor: "blue",
        awayScore: 1,
    },
    // Friday, January 10, 2025
    {
        id: "31",
        date: "Jan 10",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 4,
        awayTeam: "Kurtis",
        awayColor: "black",
        awayScore: 4,
    },
    {
        id: "32",
        date: "Jan 10",
        homeTeam: "Nick",
        homeColor: "green",
        homeScore: 13,
        awayTeam: "Ted",
        awayColor: "red",
        awayScore: 5,
    },
    {
        id: "33",
        date: "Jan 10",
        homeTeam: "Josh",
        homeColor: "blue",
        homeScore: 7,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 7,
    },
    // Friday, January 17, 2025
    {
        id: "34",
        date: "Jan 17",
        homeTeam: "Ted",
        homeColor: "red",
        homeScore: 5,
        awayTeam: "Josh",
        awayColor: "blue",
        awayScore: 15,
    },
    {
        id: "35",
        date: "Jan 17",
        homeTeam: "Kurtis",
        homeColor: "black",
        homeScore: 5,
        awayTeam: "Nick",
        awayColor: "green",
        awayScore: 11,
    },
    {
        id: "36",
        date: "Jan 17",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 1,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 5,
    },
    // Friday, January 24, 2025
    {
        id: "37",
        date: "Jan 24",
        homeTeam: "Nick",
        homeColor: "green",
        homeScore: 3,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 11,
    },
    {
        id: "38",
        date: "Jan 24",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 4,
        awayTeam: "Josh",
        awayColor: "blue",
        awayScore: 8,
    },
    {
        id: "39",
        date: "Jan 24",
        homeTeam: "Kurtis",
        homeColor: "black",
        homeScore: 10,
        awayTeam: "Ted",
        awayColor: "red",
        awayScore: 1,
    },
    // Friday, February 07, 2025
    {
        id: "40",
        date: "Feb 07",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 5,
        awayTeam: "Ted",
        awayColor: "red",
        awayScore: 2,
    },
    {
        id: "41",
        date: "Feb 07",
        homeTeam: "Kurtis",
        homeColor: "black",
        homeScore: 4,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 2,
    },
    {
        id: "42",
        date: "Feb 07",
        homeTeam: "Nick",
        homeColor: "green",
        homeScore: 5,
        awayTeam: "Josh",
        awayColor: "blue",
        awayScore: 8,
    },
    // Friday, February 14, 2025
    {
        id: "43",
        date: "Feb 14",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 2,
        awayTeam: "Kurtis",
        awayColor: "black",
        awayScore: 2,
    },
    {
        id: "44",
        date: "Feb 14",
        homeTeam: "Nick",
        homeColor: "green",
        homeScore: 14,
        awayTeam: "Ted",
        awayColor: "red",
        awayScore: 9,
    },
    {
        id: "45",
        date: "Feb 14",
        homeTeam: "Josh",
        homeColor: "blue",
        homeScore: 6,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 3,
    },
    // Friday, February 21, 2025
    {
        id: "46",
        date: "Feb 21",
        homeTeam: "Ted",
        homeColor: "red",
        homeScore: 3,
        awayTeam: "Josh",
        awayColor: "blue",
        awayScore: 11,
    },
    {
        id: "47",
        date: "Feb 21",
        homeTeam: "Kurtis",
        homeColor: "black",
        homeScore: 8,
        awayTeam: "Nick",
        awayColor: "green",
        awayScore: 7,
    },
    {
        id: "48",
        date: "Feb 21",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 1,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 10,
    },
    // Friday, February 28, 2025
    {
        id: "49",
        date: "Feb 28",
        homeTeam: "Nick",
        homeColor: "green",
        homeScore: 7,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 4,
    },
    {
        id: "50",
        date: "Feb 28",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 4,
        awayTeam: "Josh",
        awayColor: "blue",
        awayScore: 8,
    },
    {
        id: "51",
        date: "Feb 28",
        homeTeam: "Kurtis",
        homeColor: "black",
        homeScore: 11,
        awayTeam: "Ted",
        awayColor: "red",
        awayScore: 1,
    },
    // Friday, March 07, 2025
    {
        id: "52",
        date: "Mar 07",
        homeTeam: "Kurtis",
        homeColor: "black",
        homeScore: 4,
        awayTeam: "Josh",
        awayColor: "blue",
        awayScore: 10,
    },
    {
        id: "53",
        date: "Mar 07",
        homeTeam: "Ted",
        homeColor: "red",
        homeScore: 4,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 9,
    },
    {
        id: "54",
        date: "Mar 07",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 5,
        awayTeam: "Nick",
        awayColor: "green",
        awayScore: 10,
    },
    // Friday, March 14, 2025
    {
        id: "55",
        date: "Mar 14",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 6,
        awayTeam: "Ted",
        awayColor: "red",
        awayScore: 4,
    },
    {
        id: "56",
        date: "Mar 14",
        homeTeam: "Kurtis",
        homeColor: "black",
        homeScore: 5,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 5,
    },
    {
        id: "57",
        date: "Mar 14",
        homeTeam: "Nick",
        homeColor: "green",
        homeScore: 4,
        awayTeam: "Josh",
        awayColor: "blue",
        awayScore: 6,
    },
    // Friday, March 21, 2025
    {
        id: "58",
        date: "Mar 21",
        homeTeam: "Kurtis",
        homeColor: "black",
        homeScore: 3,
        awayTeam: "Josh",
        awayColor: "blue",
        awayScore: 4,
    },
    {
        id: "59",
        date: "Mar 21",
        homeTeam: "Ted",
        homeColor: "red",
        homeScore: 3,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 13,
    },
    {
        id: "60",
        date: "Mar 21",
        homeTeam: "Patrick",
        homeColor: "yellow",
        homeScore: 1,
        awayTeam: "Nick",
        awayColor: "green",
        awayScore: 7,
    },
    // Friday, March 28, 2025
    {
        id: "61",
        date: "Mar 28",
        homeTeam: "Adam",
        homeColor: "grey",
        homeScore: 17,
        awayTeam: "Ted",
        awayColor: "red",
        awayScore: 2,
    },
    {
        id: "62",
        date: "Mar 28",
        homeTeam: "Kurtis",
        homeColor: "black",
        homeScore: 2,
        awayTeam: "Patrick",
        awayColor: "yellow",
        awayScore: 1,
    },
    // Friday, April 04, 2025
    {
        id: "63",
        date: "Apr 04",
        homeTeam: "Josh",
        homeColor: "blue",
        homeScore: 2,
        awayTeam: "Kurtis",
        awayColor: "black",
        awayScore: 3,
    },
    {
        id: "64",
        date: "Apr 04",
        homeTeam: "Nick",
        homeColor: "green",
        homeScore: 10,
        awayTeam: "Adam",
        awayColor: "grey",
        awayScore: 4,
    },
    // Friday, April 11, 2025
    {
        id: "65",
        date: "Apr 11",
        homeTeam: "Kurtis",
        homeColor: "black",
        homeScore: 4,
        awayTeam: "Nick",
        awayColor: "green",
        awayScore: 8,
    },
];