// Team color mapping
export const teamColors = {
	Yellow: "#cccc00",
	Black: "#000000",
	Green: "#008000",
	Red: "#ff0000",
	Blue: "#0000ff",
	White: "#a5a5a5",
};

export const seasonMatchData = [
	{
		season: "2022/2023",
		matches: [
			{
				id: "222301",
				date: "Sep 09",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 4,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 6,
			},
			{
				id: "222302",
				date: "Sep 09",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 3,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 2,
			},
			{
				id: "222303",
				date: "Sep 09",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 7,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 3,
			},
			{
				id: "222304",
				date: "Sep 16",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 5,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 4,
			},
			{
				id: "222305",
				date: "Sep 16",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 8,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 2,
			},
			{
				id: "222306",
				date: "Sep 16",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 1,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 9,
			},
			{
				id: "222307",
				date: "Sep 23",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Adam",
				homeColor: teamColors.grey,
				homeScore: 6,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 3,
			},
			{
				id: "222308",
				date: "Sep 23",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 4,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 7,
			},
			{
				id: "222309",
				date: "Sep 23",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 2,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 10,
			},
			{
				id: "222310",
				date: "Sep 30",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 5,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 5,
			},
			{
				id: "222311",
				date: "Sep 30",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 8,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 1,
			},
			{
				id: "222312",
				date: "Sep 30",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Adam",
				homeColor: teamColors.grey,
				homeScore: 3,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 6,
			},
			{
				id: "222313",
				date: "Oct 07",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 7,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 4,
			},
			{
				id: "222314",
				date: "Oct 07",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 3,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 8,
			},
			{
				id: "222315",
				date: "Oct 07",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 2,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 4,
			},
			{
				id: "222316",
				date: "Oct 14",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 5,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 3,
			},
			{
				id: "222317",
				date: "Oct 14",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Adam",
				homeColor: teamColors.grey,
				homeScore: 9,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 6,
			},
			{
				id: "222318",
				date: "Oct 14",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 1,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 7,
			},
			{
				id: "222319",
				date: "Oct 21",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 6,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 2,
			},
			{
				id: "222320",
				date: "Oct 21",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 4,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 8,
			},
			{
				id: "222321",
				date: "Oct 21",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 7,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 3,
			},
			{
				id: "222322",
				date: "Nov 04",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Adam",
				homeColor: teamColors.grey,
				homeScore: 5,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 5,
			},
			{
				id: "222323",
				date: "Nov 04",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 6,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 4,
			},
			{
				id: "222324",
				date: "Nov 04",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 2,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 9,
			},
			{
				id: "222325",
				date: "Nov 11",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 7,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 3,
			},
			{
				id: "222326",
				date: "Nov 11",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 5,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 8,
			},
			{
				id: "222327",
				date: "Nov 11",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 3,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 6,
			},
			{
				id: "222328",
				date: "Nov 18",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 4,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 7,
			},
			{
				id: "222329",
				date: "Nov 18",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Adam",
				homeColor: teamColors.grey,
				homeScore: 2,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 5,
			},
			{
				id: "222330",
				date: "Nov 18",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 6,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 8,
			},
			{
				id: "222331",
				date: "Dec 02",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 3,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 4,
			},
			{
				id: "222332",
				date: "Dec 02",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 8,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 2,
			},
			{
				id: "222333",
				date: "Dec 02",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 6,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 5,
			},
			{
				id: "222334",
				date: "Dec 09",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 4,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 9,
			},
			{
				id: "222335",
				date: "Dec 09",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 5,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 7,
			},
			{
				id: "222336",
				date: "Dec 09",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 6,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 4,
			},
			{
				id: "222337",
				date: "Dec 16",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Adam",
				homeColor: teamColors.grey,
				homeScore: 3,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 8,
			},
			{
				id: "222338",
				date: "Dec 16",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 5,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 4,
			},
			{
				id: "222339",
				date: "Dec 16",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 7,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 2,
			},
			{
				id: "222340",
				date: "Jan 06",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 9,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 1,
			},
			{
				id: "222341",
				date: "Jan 06",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 3,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 6,
			},
			{
				id: "222342",
				date: "Jan 06",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Adam",
				homeColor: teamColors.grey,
				homeScore: 4,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 7,
			},
			{
				id: "222343",
				date: "Jan 13",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 6,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 5,
			},
			{
				id: "222344",
				date: "Jan 13",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 3,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 8,
			},
			{
				id: "222345",
				date: "Jan 13",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 2,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 4,
			},
			{
				id: "222346",
				date: "Jan 20",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 7,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 6,
			},
			{
				id: "222347",
				date: "Jan 20",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 4,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 3,
			},
			{
				id: "222348",
				date: "Jan 20",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 8,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 5,
			},
			{
				id: "222349",
				date: "Jan 27",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Adam",
				homeColor: teamColors.grey,
				homeScore: 2,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 9,
			},
			{
				id: "222350",
				date: "Jan 27",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 6,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 4,
			},
			{
				id: "222351",
				date: "Jan 27",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 7,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 3,
			},
			{
				id: "222352",
				date: "Feb 03",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 5,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 8,
			},
			{
				id: "222353",
				date: "Feb 03",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 4,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 6,
			},
			{
				id: "222354",
				date: "Feb 03",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 2,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 7,
			},
			{
				id: "222355",
				date: "Feb 10",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 6,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 3,
			},
			{
				id: "222356",
				date: "Feb 10",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Adam",
				homeColor: teamColors.grey,
				homeScore: 4,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 8,
			},
			{
				id: "222357",
				date: "Feb 10",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 5,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 2,
			},
			{
				id: "222358",
				date: "Feb 17",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 7,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 4,
			},
			{
				id: "222359",
				date: "Feb 17",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 3,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 9,
			},
			{
				id: "222360",
				date: "Feb 17",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 8,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 1,
			},
			{
				id: "222361",
				date: "Feb 24",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Adam",
				homeColor: teamColors.grey,
				homeScore: 6,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 7,
			},
			{
				id: "222362",
				date: "Feb 24",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 4,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 3,
			},
			{
				id: "222363",
				date: "Feb 24",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 5,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 6,
			},
			{
				id: "222364",
				date: "Mar 03",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 8,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 2,
			},
			{
				id: "222365",
				date: "Mar 03",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 4,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 5,
			},
			{
				id: "222366",
				date: "Mar 03",
				time: "9:30 PM",
				season: "2022/2023",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 7,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 3,
			},
			// 2022/2023 Playoffs
			{
				id: "222367",
				date: "Mar 10",
				time: "7:30 PM",
				season: "2022/2023",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 6,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 4,
				isPlayoff: true,
			},
			{
				id: "222368",
				date: "Mar 10",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 5,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 7,
				isPlayoff: true,
			},
			{
				id: "222369",
				date: "Mar 17",
				time: "8:30 PM",
				season: "2022/2023",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 8,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 3,
				isPlayoff: true,
			},
			{
				id: "222370",
				date: "Mar 24",
				time: "8:15 PM",
				season: "2022/2023",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 7,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 5,
				isPlayoff: true,
			},
		],
	},
	{
		season: "2023/2024",
		matches: [
			{
				id: "232401",
				date: "Sep 08",
				time: "7:30 PM",
				season: "2023/2024",
				homeTeam: "Adam",
				homeColor: teamColors.grey,
				homeScore: 5,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 3,
			},
			{
				id: "232402",
				date: "Sep 08",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 2,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 8,
			},
			{
				id: "232403",
				date: "Sep 08",
				time: "9:30 PM",
				season: "2023/2024",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 6,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 4,
			},
			{
				id: "232404",
				date: "Sep 15",
				time: "7:30 PM",
				season: "2023/2024",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 7,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 3,
			},
			{
				id: "232405",
				date: "Sep 15",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 4,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 5,
			},
			{
				id: "232406",
				date: "Sep 15",
				time: "9:30 PM",
				season: "2023/2024",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 9,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 2,
			},
			{
				id: "232407",
				date: "Sep 22",
				time: "7:30 PM",
				season: "2023/2024",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 3,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 7,
			},
			{
				id: "232408",
				date: "Sep 22",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 5,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 6,
			},
			{
				id: "232409",
				date: "Sep 22",
				time: "9:30 PM",
				season: "2023/2024",
				homeTeam: "Adam",
				homeColor: teamColors.grey,
				homeScore: 2,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 8,
			},
			{
				id: "232410",
				date: "Sep 29",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 4,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 6,
			},
			{
				id: "232411",
				date: "Oct 06",
				time: "7:30 PM",
				season: "2023/2024",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 9,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 2,
			},
			{
				id: "232412",
				date: "Oct 06",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 3,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 8,
			},
			{
				id: "232413",
				date: "Oct 06",
				time: "9:30 PM",
				season: "2023/2024",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 5,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 6,
			},
			{
				id: "232414",
				date: "Oct 13",
				time: "7:30 PM",
				season: "2023/2024",
				homeTeam: "Adam",
				homeColor: teamColors.grey,
				homeScore: 4,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 7,
			},
			{
				id: "232415",
				date: "Oct 13",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 6,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 3,
			},
			{
				id: "232416",
				date: "Oct 13",
				time: "9:30 PM",
				season: "2023/2024",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 5,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 8,
			},
			{
				id: "232417",
				date: "Oct 20",
				time: "7:30 PM",
				season: "2023/2024",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 2,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 9,
			},
			{
				id: "232418",
				date: "Oct 20",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 4,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 6,
			},
			{
				id: "232419",
				date: "Oct 20",
				time: "9:30 PM",
				season: "2023/2024",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 7,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 5,
			},
			{
				id: "232420",
				date: "Nov 03",
				time: "7:30 PM",
				season: "2023/2024",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 8,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 3,
			},
			{
				id: "232421",
				date: "Nov 03",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Adam",
				homeColor: teamColors.grey,
				homeScore: 4,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 7,
			},
			{
				id: "232422",
				date: "Nov 03",
				time: "9:30 PM",
				season: "2023/2024",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 6,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 5,
			},
			{
				id: "232423",
				date: "Nov 10",
				time: "7:30 PM",
				season: "2023/2024",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 9,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 2,
			},
			{
				id: "232424",
				date: "Nov 10",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 3,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 8,
			},
			{
				id: "232425",
				date: "Nov 10",
				time: "9:30 PM",
				season: "2023/2024",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 5,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 4,
			},
			{
				id: "232426",
				date: "Nov 17",
				time: "7:30 PM",
				season: "2023/2024",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 6,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 7,
			},
			{
				id: "232427",
				date: "Nov 17",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 8,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 3,
			},
			{
				id: "232428",
				date: "Nov 17",
				time: "9:30 PM",
				season: "2023/2024",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 5,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 6,
			},
			{
				id: "232429",
				date: "Dec 01",
				time: "7:30 PM",
				season: "2023/2024",
				homeTeam: "Adam",
				homeColor: teamColors.grey,
				homeScore: 4,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 9,
			},
			{
				id: "232430",
				date: "Dec 01",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 7,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 2,
			},
			{
				id: "232431",
				date: "Dec 01",
				time: "9:30 PM",
				season: "2023/2024",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 3,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 8,
			},
			{
				id: "232432",
				date: "Dec 08",
				time: "7:30 PM",
				season: "2023/2024",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 6,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 4,
			},
			{
				id: "232433",
				date: "Dec 08",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 5,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 7,
			},
			{
				id: "232434",
				date: "Dec 08",
				time: "9:30 PM",
				season: "2023/2024",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 3,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 6,
			},
			{
				id: "232435",
				date: "Dec 15",
				time: "7:30 PM",
				season: "2023/2024",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 8,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 5,
			},
			{
				id: "232436",
				date: "Dec 15",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 4,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 9,
			},
			{
				id: "232437",
				date: "Dec 15",
				time: "9:30 PM",
				season: "2023/2024",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 3,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 7,
			},
			{
				id: "232438",
				date: "Jan 05",
				time: "7:30 PM",
				season: "2023/2024",
				homeTeam: "Adam",
				homeColor: teamColors.grey,
				homeScore: 6,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 4,
			},
			{
				id: "232439",
				date: "Jan 05",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 5,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 8,
			},
			{
				id: "232440",
				date: "Jan 05",
				time: "9:30 PM",
				season: "2023/2024",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 2,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 7,
			},
			{
				id: "232441",
				date: "Jan 12",
				time: "7:30 PM",
				season: "2023/2024",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 8,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 3,
			},
			{
				id: "232442",
				date: "Jan 12",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 5,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 6,
			},
			{
				id: "232443",
				date: "Jan 12",
				time: "9:30 PM",
				season: "2023/2024",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 4,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 9,
			},
			{
				id: "232444",
				date: "Jan 19",
				time: "7:30 PM",
				season: "2023/2024",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 7,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 5,
			},
			{
				id: "232445",
				date: "Jan 19",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 3,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 6,
			},
			{
				id: "232446",
				date: "Jan 19",
				time: "9:30 PM",
				season: "2023/2024",
				homeTeam: "Adam",
				homeColor: teamColors.grey,
				homeScore: 4,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 8,
			},
			{
				id: "232447",
				date: "Jan 26",
				time: "7:30 PM",
				season: "2023/2024",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 6,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 3,
			},
			{
				id: "232448",
				date: "Jan 26",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 2,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 9,
			},
			{
				id: "232449",
				date: "Jan 26",
				time: "9:30 PM",
				season: "2023/2024",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 7,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 4,
			},
			// Playoffs
			{
				id: "232450",
				date: "Mar 08",
				time: "7:30 PM",
				season: "2023/2024",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 8,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 6,
				isPlayoff: true,
			},
			{
				id: "232451",
				date: "Mar 08",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 5,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 7,
				isPlayoff: true,
			},
			{
				id: "232452",
				date: "Mar 15",
				time: "8:30 PM",
				season: "2023/2024",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 6,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 4,
				isPlayoff: true,
			},
			{
				id: "232453",
				date: "Mar 22",
				time: "8:15 PM",
				season: "2023/2024",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 9,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 5,
				isPlayoff: true,
			},
		],
	},
	{
		season: "2024/2025",
		matches: [
			{
				id: "242501",
				date: "Oct 25",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 3,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 3,
			},
			{
				id: "242502",
				date: "Oct 25",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 5,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 2,
			},
			{
				id: "242503",
				date: "Oct 25",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 7,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 3,
			},
			{
				id: "242504",
				date: "Nov 01",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 1,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 10,
			},
			{
				id: "202405",
				date: "Nov 01",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 3,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 6,
			},
			{
				id: "242506",
				date: "Nov 01",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 2,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 7,
			},
			{
				id: "242507",
				date: "Nov 08",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 4,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 5,
			},
			{
				id: "242508",
				date: "Nov 08",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 4,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 8,
			},
			{
				id: "242509",
				date: "Nov 08",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 11,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 1,
			},
			{
				id: "242510",
				date: "Nov 15",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 1,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 6,
			},
			{
				id: "242511",
				date: "Nov 15",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 0,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 12,
			},
			{
				id: "242512",
				date: "Nov 15",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 3,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 11,
			},
			{
				id: "242513",
				date: "Nov 22",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 3,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 3,
			},
			{
				id: "242514",
				date: "Nov 22",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 2,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 5,
			},
			{
				id: "242515",
				date: "Nov 22",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 6,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 5,
			},
			{
				id: "242516",
				date: "Nov 29",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 3,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 4,
			},
			{
				id: "242517",
				date: "Nov 29",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 11,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 0,
			},
			{
				id: "242518",
				date: "Nov 29",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 2,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 1,
			},
			{
				id: "242519",
				date: "Dec 06",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 2,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 10,
			},
			{
				id: "242520",
				date: "Dec 06",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 3,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 5,
			},
			{
				id: "242521",
				date: "Dec 06",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 3,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 4,
			},
			{
				id: "242522",
				date: "Dec 13",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 4,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 8,
			},
			{
				id: "242523",
				date: "Dec 13",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 3,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 6,
			},
			{
				id: "242524",
				date: "Dec 13",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 4,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 4,
			},
			{
				id: "242525",
				date: "Dec 20",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 4,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 12,
			},
			{
				id: "242526",
				date: "Dec 20",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 1,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 7,
			},
			{
				id: "242527",
				date: "Dec 20",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 4,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 14,
			},
			{
				id: "242528",
				date: "Jan 03",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 2,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 4,
			},
			{
				id: "242529",
				date: "Jan 03",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 7,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 3,
			},
			{
				id: "242530",
				date: "Jan 03",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 2,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 1,
			},
			{
				id: "242531",
				date: "Jan 10",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 4,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 4,
			},
			{
				id: "242532",
				date: "Jan 10",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 13,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 5,
			},
			{
				id: "242533",
				date: "Jan 10",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 7,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 7,
			},
			{
				id: "242534",
				date: "Jan 17",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 5,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 15,
			},
			{
				id: "242535",
				date: "Jan 17",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 5,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 11,
			},
			{
				id: "242536",
				date: "Jan 17",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 1,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 5,
			},
			{
				id: "242537",
				date: "Jan 24",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 3,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 11,
			},
			{
				id: "242538",
				date: "Jan 24",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 4,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 8,
			},
			{
				id: "242539",
				date: "Jan 24",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 10,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 1,
			},
			{
				id: "242540",
				date: "Feb 07",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 5,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 2,
			},
			{
				id: "242541",
				date: "Feb 07",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 4,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 2,
			},
			{
				id: "242542",
				date: "Feb 07",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 5,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 8,
			},
			{
				id: "242543",
				date: "Feb 14",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 2,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 2,
			},
			{
				id: "242544",
				date: "Feb 14",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 14,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 9,
			},
			{
				id: "242545",
				date: "Feb 14",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 6,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 3,
			},
			{
				id: "242546",
				date: "Feb 21",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 3,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 11,
			},
			{
				id: "242547",
				date: "Feb 21",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 8,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 7,
			},
			{
				id: "242548",
				date: "Feb 21",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 1,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 10,
			},
			{
				id: "242549",
				date: "Feb 28",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 7,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 4,
			},
			{
				id: "242550",
				date: "Feb 28",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 4,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 8,
			},
			{
				id: "242551",
				date: "Feb 28",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 11,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 1,
			},
			{
				id: "242552",
				date: "Mar 07",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 4,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 10,
			},
			{
				id: "242553",
				date: "Mar 07",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 4,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 9,
			},
			{
				id: "242554",
				date: "Mar 07",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 5,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 10,
			},
			{
				id: "242555",
				date: "Mar 14",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 6,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 4,
			},
			{
				id: "242556",
				date: "Mar 14",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 5,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 5,
			},
			{
				id: "242557",
				date: "Mar 14",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 4,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 6,
			},
			{
				id: "242558",
				date: "Mar 21",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 3,
				awayTeam: "Josh",
				awayColor: teamColors.Blue,
				awayScore: 4,
			},
			{
				id: "242559",
				date: "Mar 21",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Ted",
				homeColor: teamColors.Red,
				homeScore: 3,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 13,
			},
			{
				id: "242560",
				date: "Mar 21",
				time: "9:30 PM",
				season: "2024/2025",
				homeTeam: "Patrick",
				homeColor: teamColors.Yellow,
				homeScore: 1,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 7,
			},
			// Playoffs
			{
				id: "242561",
				date: "Mar 28",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Adam",
				homeColor: teamColors.grey,
				homeScore: 17,
				awayTeam: "Ted",
				awayColor: teamColors.Red,
				awayScore: 2,
				isPlayoff: true,
			},
			{
				id: "242562",
				date: "Mar 28",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 2,
				awayTeam: "Patrick",
				awayColor: teamColors.Yellow,
				awayScore: 1,
				isPlayoff: true,
			},
			{
				id: "242563",
				date: "Apr 04",
				time: "7:30 PM",
				season: "2024/2025",
				homeTeam: "Josh",
				homeColor: teamColors.Blue,
				homeScore: 2,
				awayTeam: "Kurtis",
				awayColor: teamColors.Black,
				awayScore: 3,
				isPlayoff: true,
			},
			{
				id: "242564",
				date: "Apr 04",
				time: "8:30 PM",
				season: "2024/2025",
				homeTeam: "Nick",
				homeColor: teamColors.Green,
				homeScore: 10,
				awayTeam: "Adam",
				awayColor: teamColors.grey,
				awayScore: 4,
				isPlayoff: true,
			},
			{
				id: "242565",
				date: "Apr 11",
				time: "8:15 PM",
				season: "2024/2025",
				homeTeam: "Kurtis",
				homeColor: teamColors.Black,
				homeScore: 4,
				awayTeam: "Nick",
				awayColor: teamColors.Green,
				awayScore: 8,
				isPlayoff: true,
			},
		],
	}
];